# Generated by Django 3.2.13 on 2022-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_job_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_image',
            field=models.ImageField(blank=True, default='../static/images/job5.jpg', null=True, upload_to='job/image/'),
        ),
    ]
