# Generated by Django 3.2.13 on 2022-05-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_allchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allchat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='allchat',
            name='user',
        ),
        migrations.AddField(
            model_name='allchat',
            name='user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
