# Generated by Django 3.2.6 on 2022-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220527_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='allchat',
            name='chat',
            field=models.ManyToManyField(to='app.Chat'),
        ),
    ]
