# Generated by Django 3.2.6 on 2022-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_jobcrawl_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcrawl',
            name='job_description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
