# Generated by Django 3.2.6 on 2022-06-03 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_jobcrawl_job_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcrawl',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='allchat',
            old_name='user_mail',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='job_user_mail',
        ),
        migrations.AddField(
            model_name='allchat',
            name='user_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
