# Generated by Django 3.2.6 on 2022-06-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220603_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allchat',
            old_name='job',
            new_name='job_anonymous',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='job',
            new_name='job_anonymous',
        ),
    ]
