# Generated by Django 3.2.6 on 2022-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220605_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcrawl',
            name='status',
        ),
        migrations.AddField(
            model_name='jobcrawl',
            name='job_image_link',
            field=models.URLField(null=True),
        ),
    ]
