# Generated by Django 3.2.6 on 2022-06-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220606_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcrawl',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobcrawl',
            name='job_image_link',
        ),
    ]
